default_model = "local"

[models]

[models.local]
provider = "local"
model_name = "gpt-oss:20b"
base_url = "http://127.0.0.1:11434/v1"

[models.openai]
provider = "openai"
model_name = "gpt-4.1"

[models.gemini]
provider = "gemini"
model_name = "gemini-2.5-flash"