name = "AugmentedAwareness"
uuid = "a69c55ff-83c5-459b-a5e2-ea3ec707f11e"
authors = ["Roberto Lupi <roberto.lupi@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
HTTP = "1.10.16"
JSON = "0.21.4"
YAML = "0.4.13"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
